version: '3'
services:
  db-hm-security:
    image: postgres:12
    container_name: db-security
    restart: always
    ports:
      - "5454:5432"
    networks:
      - handmall-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin567
      POSTGRES_DB: hm-security

  db-hm-department:
    image: postgres:12
    container_name: db-department
    restart: always
    ports: 
      - "5455:5432"
    networks:
      - handmall-network
    environment: 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hm-department

  db-hm-vendor:
    image: postgres:12
    container_name: db-vendor
    restart: always
    ports:
      - "5456:5432"
    networks:
      - handmall-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hm-vendor

  db-hm-product:
    image: postgres:12
    container_name: db-product
    restart: always
    ports:
      - "5457:5432"
    networks:
      - handmall-network
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: hm-product

  db-admin-handmall-api:
    image: adminer
    container_name: db-admin
    restart: always
    ports:
      - "8831:8080"
    networks:
      - handmall-network

  hm-zipkin:
    image: openzipkin/zipkin
    container_name: hm-zipkin
    restart: always
    ports:
      - "9411:9411"
    networks:
      - handmall-network

  hm-rabbitmq:
    image: rabbitmq:3.12.1-management-alpine
    container_name: hm-rabbitmq
    restart: on-failure
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - handmall-network
  
networks:
  handmall-network: